---
name: Run yamllint

on:
  - push
  - pull_request

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v1
        with:
          file_or_dir: .
          config_file: .yamllint.yml
